@startuml
participant "Waiting Lounge" 

box "Line A"
participant "Module A1"
queue "Buffer A1.2"
queue "Buffer A1.1"
participant "Module A2"
queue "Buffer A2.2"
queue "Buffer A2.1"
participant "Module A3"
end box

box "Line B"
participant "Module B1"
queue "Buffer B1.1"
queue "Buffer B1.2"
participant "Module B2"
queue "Buffer B2.1"
queue "Buffer B2.2"
participant "Module B3"
end box

"Waiting Lounge" -> "Module 1"
"Module 1" -> "Module 2"
"Module 2" -> "Module 3"

@enduml